server.port=9090
spring.application.name=stats-server

# Database configuration
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/ewm-stats
spring.datasource.username=ewm_user
spring.datasource.password=ewm_password

# JPA configuration
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

# schema.sql
spring.sql.init.mode=always

# Logging
logging.level.ru.practicum=DEBUG
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=DEBUG