-- Создание таблицы для хранения статистики запросов

CREATE TABLE IF NOT EXISTS endpoint_hits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app VARCHAR(255) NOT NULL,
    uri VARCHAR(255) NOT NULL,
    ip VARCHAR(45) NOT NULL,
    timestamp TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

-- Индексы для оптимизации запросов статистики
CREATE INDEX IF NOT EXISTS idx_endpoint_hits_timestamp ON endpoint_hits(timestamp);
CREATE INDEX IF NOT EXISTS idx_endpoint_hits_uri ON endpoint_hits(uri);
CREATE INDEX IF NOT EXISTS idx_endpoint_hits_timestamp_uri ON endpoint_hits(timestamp, uri);
CREATE INDEX IF NOT EXISTS idx_endpoint_hits_app ON endpoint_hits(app);

-- Индекс для быстрого поиска по uri с сортировкой по времени
CREATE INDEX IF NOT EXISTS idx_endpoint_hits_uri_timestamp ON endpoint_hits(uri, timestamp);

-- Индекс для подсчета уникальных IP
CREATE INDEX IF NOT EXISTS idx_endpoint_hits_ip_timestamp ON endpoint_hits(ip, timestamp);

-- Композитный индекс для частых запросов статистики
CREATE INDEX IF NOT EXISTS idx_endpoint_hits_uri_timestamp_ip ON endpoint_hits(uri, timestamp, ip);